config/routes.rb
Rails.application.routes.draw do
  resources :station_sensors
  resources :sensors
  resources :stations
  
  get 'stations/:id/active/:status' => 'stations#active', as: 'active_stations'
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  validates :nombre, presence: true
end

app/models/station.rb
class Station < ActiveRecord::Base
  #Asociaciones
  has_many :station_sensors
  has_many :sensors, through: :station_sensors

  #Validaciones
  validates :nombre, presence: true

  #Callbacks
  before_create :before_create_callback

  private
  def before_create_callback
    self.deleted = false
    self.enabled = true
  end
end

app/models/station_sensor.rb
class StationSensor < ActiveRecord::Base
  #Asociaciones
  belongs_to :station
  belongs_to :sensor
  has_many :station_sensor_measurements
end

app/models/station_sensor_measurement.rb
class StationSensorMeasurement < ActiveRecord::Base
  #Asociaciones
  belongs_to :station_sensor
  
  #Validaciones
  validates :medida, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:nombre, :descripcion, :deleted)
    end
end

app/controllers/station_sensors_controller.rb
class StationSensorsController < ApplicationController
  before_action :set_station_sensor, only: [:show, :edit, :update, :destroy]

  # GET /station_sensors
  # GET /station_sensors.json
  def index
    @station_sensors = StationSensor.all
  end

  # GET /station_sensors/1
  # GET /station_sensors/1.json
  def show
  end

  # GET /station_sensors/new
  def new
    @station_sensor = StationSensor.new
    @stations = Station.all
    @sensors = Sensor.all
  end

  # GET /station_sensors/1/edit
  def edit
  end

  # POST /station_sensors
  # POST /station_sensors.json
  def create
    @station_sensor = StationSensor.new(station_sensor_params)

    respond_to do |format|
      if @station_sensor.save
        format.html { redirect_to @station_sensor, notice: 'Station sensor was successfully created.' }
        format.json { render :show, status: :created, location: @station_sensor }
      else
        format.html { render :new }
        format.json { render json: @station_sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /station_sensors/1
  # PATCH/PUT /station_sensors/1.json
  def update
    respond_to do |format|
      if @station_sensor.update(station_sensor_params)
        format.html { redirect_to @station_sensor, notice: 'Station sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @station_sensor }
      else
        format.html { render :edit }
        format.json { render json: @station_sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /station_sensors/1
  # DELETE /station_sensors/1.json
  def destroy
    @station_sensor.destroy
    respond_to do |format|
      format.html { redirect_to station_sensors_url, notice: 'Station sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station_sensor
      @station_sensor = StationSensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_sensor_params
      params.require(:station_sensor).permit(:station_id, :sensor_id)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy, :active]

  # GET /stations
  # GET /stations.json
  def index
    @page = params[:page] || 1
    @stations = Station.order(enabled: :desc).paginate(per_page: 30, page: @page)
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    status = params[:status]
    real_status = (status == 'true' ? true : false)
    @station.destroy = real_status


    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def active
    status = params[:status]
    real_status = (status == 'true' ? true : false)
    @station.enabled = real_status


    respond_to do |format|
      if @station.save
        format.json{head :no_content, status: :ok}
      else
        format.json{head :no_content, status: :unprocessable_entity}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:nombre, :descripcion, :deleted, :enabled)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/helpers/station_sensors_helper.rb
module StationSensorsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title><%= content_for?(:title) ? yield(:title) : "Monitoreo Climatico" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= yield :head %>
  </body>
</html>

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.nombre %></td>
        <td><%= sensor.descripcion %></td>
        <td><%= sensor.deleted %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @sensor.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @sensor.descripcion %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @sensor.deleted %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>

app/views/shared/_admin_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Monitoreo Climático</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li <%= page == 'root' ? "class=active" : ''%>><a href="#">Home</a></li>
        <li <%= page == 'stations' ? "class=active" : ''%>><%=link_to 'Estaciones', :stations %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div class="separatenav"></div>

app/views/station_sensors/_form.html.erb
<%= form_for(@station_sensor) do |f| %>
  <% if @station_sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station_sensor.errors.count, "error") %> prohibited this station_sensor from being saved:</h2>

      <ul>
      <% @station_sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :station_id %><br>
    <%=f.select(:station_id, options_from_collection_for_select(@stations,'id','nombre'))%>
  </div>
  <div class="field">
    <%= f.label :sensor_id %><br>
    <%=f.select(:sensor_id, options_from_collection_for_select(@sensors,'id','nombre'))%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/station_sensors/edit.html.erb
<h1>Editing Station Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @station_sensor %> |
<%= link_to 'Back', station_sensors_path %>

app/views/station_sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Station Sensors</h1>

<table>
  <thead>
    <tr>
      <th>Station</th>
      <th>Sensor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @station_sensors.each do |station_sensor| %>
      <tr>
        <td><%= station_sensor.station.nombre %></td>
        <td><%= station_sensor.sensor.nombre %></td>
        <td><%= link_to 'Show', station_sensor %></td>
        <td><%= link_to 'Edit', edit_station_sensor_path(station_sensor) %></td>
        <td><%= link_to 'Destroy', station_sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station sensor', new_station_sensor_path %>

app/views/station_sensors/new.html.erb
<h1>New Station Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', station_sensors_path %>

app/views/station_sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station:</strong>
  <%= @station_sensor.station %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @station_sensor.sensor %>
</p>

<%= link_to 'Edit', edit_station_sensor_path(@station_sensor) %> |
<%= link_to 'Back', station_sensors_path %>

app/views/stations/_form.html.erb
<% if @station.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

    <ul>
    <% @station.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :nombre %>
  <%= f.text_field :nombre, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :descripcion %>
  <%= f.text_area :descripcion, class: "form-control" %>
</div>

app/views/stations/_stations.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
        <tr>
          <th class="text-center">Nombre</th>
          <th class="text-center">Mostrar</th>
          <th class="text-center">Editar</th>
          <th class="text-center">Activa</th>
          <th class="text-center">Borrado</th>
        </tr>
      </thead>
      <tbody>
        <%@stations.each do |station|%>
          <tr>
            <td class="text-center"><%=station.nombre%></td>
            <td class="text-center"><%= link_to "<i class='fa fa-eye fa-2x hvr-grow'></i>".html_safe, station_path(station)%></td>
            <td class="text-center"><%= link_to "<i class='fa fa-pencil-square-o fa-2x hvr-grow'></i>".html_safe, edit_station_path(station) %></td>
            <td class="text-center"><%= check_box_tag 'station_active', station.id, station.enabled, class: 'checkbox_active'%></td>
            <td class="text-center"><%= check_box_tag 'station_status', station.id, station.deleted, class: 'checkbox_deleted'%></td>
          </tr>
        <%end%>
      </tbody>
  </table>
</div>

app/views/stations/edit.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'stations', :media => 'all' %>
  <%= stylesheet_link_tag 'jquery-ui.min', :media => 'all' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag 'jquery.validate' %>
  <%= javascript_include_tag 'additional-methods' %>
  <%= javascript_include_tag 'stations' %>
<% end %>
<%=render 'shared/admin_menu', page: 'stations'%>
<div id="container" class="container">
  <h1>Editar Estación</h1>
  <div class="col-md-3">
    <%= form_for(@station) do |f| %>
      <%= render 'form', f: f%>
      <div class="actions">
        <%= f.submit 'Editar', class: "btn btn-info"%>
      </div>
    <%end%>
  </div>
</div>

app/views/stations/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'jquery-ui.min', :media => 'all' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag 'jquery.validate' %>
  <%= javascript_include_tag 'additional-methods' %>
  <%= javascript_include_tag 'stations' %>
<% end %>
<%=render 'shared/admin_menu', page: 'stations'%>
<div id="container" class="container">
  <h2>Estaciones</h2>
	<div class="col-md-2 col-xs-12 text-center">	
		<%=link_to "<i class='fa fa-plus-circle fa-2x'></i></br>Agregar".html_safe,new_station_path, class: 'btn btn-primary botones' %>
		<%=link_to "<i class='fa fa-refresh fa-2x'></i></br>Actualizar".html_safe,stations_path(page: @page), class: 'btn btn-info botones' %>
	</div>
	<div class="col-md-10 col-xs-12">
		<div class="row">
	    <%=form_tag('#', method: :get) do%>
		    <div class="col-md-8">
		      <div class="row collapse">
	      		<div class="col-xs-10">
		          <%=text_field_tag(:search_hint, '', placeholder: 'Buscar')%>
		        </div>
		        <div class="col-xs-2">
		        	<%=submit_tag 'Buscar', class: 'button postfix'%>
		        </div>
		      </div>
		    </div>
	    <%end%>
	  </div>
		<% if flash[:notice]%>
			<div data-alert class="alert-box success radius">
	  		<%= flash[:notice]%>
	  		<a href="#" class="close">&times;</a>
			</div>
		<% end %>
		<%= render 'stations'%>
	</div>
</div>

app/views/stations/new.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'stations', :media => 'all' %>
  <%= stylesheet_link_tag 'jquery-ui.min', :media => 'all' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag 'jquery.validate' %>
  <%= javascript_include_tag 'additional-methods' %>
  <%= javascript_include_tag 'stations' %>
<% end %>
<%=render 'shared/admin_menu', page: 'stations'%>
<div id="container" class="container">
  <h2>Crear Estación</h2>
  <div class="col-md-3">
    <%= form_for(@station) do |f| %>
      <%= render 'form', f: f%>
      <div class="actions">
        <%= f.submit 'Crear', class: "btn btn-info"%>
      </div>
    <%end%>
  </div>
</div>

app/views/stations/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'jquery-ui.min', :media => 'all' %>
  <%= stylesheet_link_tag 'stations', :media => 'all' %>
  <%= javascript_include_tag 'jquery-ui.min' %>
  <%= javascript_include_tag 'jquery.validate' %>
  <%= javascript_include_tag 'additional-methods' %>
  <%= javascript_include_tag 'stations' %>
<% end %>
<%=render 'shared/admin_menu', page: 'stations'%>
<div id="container" class="container">
  <div class="col-md-4" id="info">
      <p>
        <strong>Nombre:</strong>
        <%= @station.nombre %>
      </p>
      <p>
        <strong>Descripcion:</strong>
        <%= @station.descripcion %>
      </p>
  </div>
</div>